#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo -e "\033[0;31mPlease run as root"
  exit
fi


echo "<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /home/mena/Desktop/php
ErrorLog \${APACHE_LOG_DIR}/error.log
	CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$1.conf

echo "127.0.0.1  $1" > /etc/hosts 
a2ensite $1.conf
service apache2 restart